name: fer
channels:
  - defaults
dependencies:
  - python=3.8.2
  - pip
  - Flask=1.1.2
  - Pillow=6.2.1
  - scikit-learn=0.22.1
  - scikit-image=0.17.2
  - gunicorn=20.0.4
  - numpy=1.20.2
  - Pillow=6.2.1
  - pip:
    - opencv-python-headless==4.2.0.34
    - smart-open==5.1.0